name: CI/CD

on: [push]

jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: npm ci
            - run: npm run build

    test: 
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Cypress run
              uses: cypress-io/github-action@v6
              with:
                build: npm run build
                start: npm start
                browser: chrome
            - uses : actions/uploads-artifact@v3
              if: always()
              with:
                name: cypress-videos
                path: cypress/videos  
